### PR TITLE
BAU: Update nginx to log message in JSON format by default

### PR DESCRIPTION
**Pull request by adityapahuja**
This will enable journalbeat to be able to decode nginx JSON log message to make it easier to see what is going on in Kibana. The nginx json log format is taken from nginx config file in old infrastructure. This will keep the nginx log format same between old and new infrastructure.

Author: @adityapahuja

### CODE REVIEW

**Comment by tlwr** [comment]
How to review

```
cd verify-infrastructure/dockerfiles/nginx-tls
docker build -t nginx .
docker run --name test-pr-160 -d -p 8443:8443 -e LOCATION_BLOCKS='IAo=' nginx
sleep 10
curl https://localhost:8443 -vvv
docker logs test-pr-160
```

**Comment by philandstuff** [comment]
🤔 I tested it and got

```
Generating a RSA private key
............................................+++++
...............................................................+++++
writing new private key to '/tmp/tls/key.pem'
-----
{ "@timestamp": "2019-03-07T16:05:06+00:00", "@message": "GET / HTTP/1.1", "@fields": { "remote_addr": "172.17.0.1", "remote_user": "-", "body_bytes_sent": 153, "bytes_sent": 308, "request_time": 0.000, "upstream_response_time": "-", "upstream_addr": "-", "gzip_ratio": "-", "sent_http_x_cache": "-", "sent_http_location": "-", "http_host": "localhost:8443", "server_name": "", "server_port": "8443", "status": 404, "request": "GET / HTTP/1.1", "content_type": "-", "request_method": "GET", "http_referrer": "-", "http_user_agent": "curl/7.54.0", "http_x_forwarded_for": "-", "ssl_cipher": "ECDHE-RSA-AES256-GCM-SHA384", "ssl_protocol": "TLSv1.2", "ssl_session_reused": ".", "msec": "1551974706.169", "connection": "2", "session_id_cookie": "-", "augur_cookie": "-", "ssl_client_s_dn": "-", "upstream_cookie_x_govuk_session_cookie": "-"} }
```

this is not *entirely* JSON. Will this cause problems?

Also, what happens to nginx error logs? (what happens to them now, and what happens after this PR?)

**Comment by adityapahuja** [comment]
The first five lines come from openssl  in docker-entrypoint.sh script. Openssl does not output in JSON format. 
The last line comes from nginx.

**Comment by adityapahuja** [comment]
I have fixed it.

**Comment by sakisv** [comment]
> How to review
> 
> ```
> ....
> docker run --name test-pr-160 -d -p 8443:8443 -e LOCATION_BLOCKS='IAo=' nginx
> ....
> ```

@tlwr what does the `LOCATION_BLOCKS='IAo='` do here?

**Comment by andy-paine** [comment]
```echo " " | base64
IAo=``` lol

**Comment by adityapahuja** [comment]
`'IAo='` is a space character. If we have not defined the environment variable `LOCATION_BLOCKS='IA0='`, docker logs will not output openssl message and instead it will show an error message `/tmp/docker-entrypoint.sh: line 4: LOCATION_BLOCKS: LOCATION_BLOCKS not set`. I wonder if we can get the shell script to output the error message in JSON format.

**Pull request merged**
