### PR TITLE
AUTO: Only alert if saml stays unreliable

### PR DESCRIPTION
**Pull request by andy-paine**
- We were previously testing "has the success % of SAML requests dropped
  below 95% in the last 15 minutes"
- We want to test "has the success % of SAML requests stayed below 95%
  for the last 15 minutes"
- This is basically testing if the max is below 95% for 15 mins so just
  swap min -> max

### CODE REVIEW

**Comment by issyl0** [comment]
Ahh, we've not moved this out of Grafana yet, that's why I couldn't find it when I was looking for alertmanager?

**Comment by issyl0** [comment]
Is this still relevant given Toby has disabled Grafana alerting?

**Comment by andy-paine** [comment]
https://prom-1.mgmt.signin.service.gov.uk/alerts suggests that they have been moved?

**Comment by issyl0** [comment]
I'm confused.

**Comment by issyl0** [comment]
Closing this as these alerts have been removed from Grafana in #172.

**Pull request closed without merging**
