### PR TITLE
hub deployer role: deny ability to release elastic IPs

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/lQs5jsln

We don't want this happening accidentally as our IPs tend to be specially
blessed elsewhere.

### CODE REVIEW

**Review by blairboy362 — DISMISSED** [review]

**Review by Krenair — APPROVED** [review]

**Comment by Krenair** [comment]
Just noticed something - this is a statement in the assume role policy, rather than a policy attached to the role e.g. administrator

**Review by blairboy362 — APPROVED** [review]

**Review by Krenair — APPROVED** [review]

**Comment by risicle** [comment]
What I've done is an "inline policy", right?

**Comment by risicle** [comment]
Oh and and an `assume_role_policy` is something totally different..

**Comment by Krenair** [comment]
yep, and yes. assume role policies are used to define who can assume a role, what we want to do here is define the permissions of the role itself :)

**Pull request merged**
